import 'dart:async';

import 'package:get_it/get_it.dart';
import 'package:jwt_decoder/jwt_decoder.dart';
import 'package:shared_preferences/shared_preferences.dart';

import '../../http/set_jwt_header.dart';
import 'update_jwt.dart';

/// Checks if there is a jwt key exists in the local storage and is valid.
///
/// If the token is valid, it is set to the http client for future requests.
/// If the token is missing or expired, the http client's JWT header is cleared,
/// and the expired token is removed from [SharedPreferences].
bool isAuthenticated() {
  final prefs = GetIt.I.get<SharedPreferences>();
  final String? jwt = prefs.getString('jwt');

  if (jwt == null || JwtDecoder.isExpired(jwt)) {
    /// This operation imediatly removes any JWT from the http client, and, as
    /// a synchronous operation, removes any value from the local storage.
    ///
    /// The second operation does not usually takes more that some milliseconds.
    /// And since, a new JWT is only generated by making a new http request,
    /// which takes much longer, we can safely not wait for this operation to
    /// finish.
    unawaited(updateJwt(null));

    return false;
  }
  setJwtHeader(jwt);
  return true;
}
